const BootActionTypes = {
  GET_BACKGROUNDS: 'GET_BACKGROUNDS',
  SET_LOCK_SCREEN_BACKGROUND: 'SET_LOCK_SCREEN_BACKGROUND',
  SET_LOGIN_SCREEN_BACKGROUND: 'SET_LOGIN_SCREEN_BACKGROUND'
};

export default BootActionTypes;