const AccountActionTypes = {
  LOAD_ACCOUNT: 'LOAD_ACCOUNT',
  GET_ACCOUNT_SETTINGS: 'GET_ACCOUNT_SETTINGS',
  GET_FILESYSTEM: 'GET_FILESYSTEM',

  CREATE_NEW_DIR_ITEM: 'CREATE_NEW_DIR_ITEM',
};

export default AccountActionTypes;