const AccountActionTypes = {
  LOAD_ACCOUNT: 'LOAD_ACCOUNT',
  GET_ACCOUNT_SETTINGS: 'GET_ACCOUNT_SETTINGS',
  GET_FILESYSTEM: 'GET_FILESYSTEM',
  SAVE_ACCOUNT: 'SAVE_ACCOUNT',

  CREATE_NEW_DIR_ITEM: 'CREATE_NEW_DIR_ITEM',
  RENAME_DIR_ITEM: 'RENAME_DIR_ITEM',
  DELETE_DIR_ITEM: 'DELETE_DIR_ITEM',
  COPY_DIR_ITEM: 'COPY_DIR_ITEM',
  MOVE_DIR_ITEM: 'MOVE_DIR_ITEM',
};

export default AccountActionTypes;
